<div>
    <h3><a ui-sref="download({ version: 'beta:0.3.7' })">DOWNLOAD BETA v0.3.7</a></h3>
    <h1>NOTABLE CHANGES</h1>
    <div id="release-notes" class="release-notes" style="margin-bottom: 20px;">
        <div id="thread_local" class="release-note">
            <h4>Added thread_local annotation modifier</h4>
            <p>
                As explained in <a ui-sref="blog.thread-local-storage">this blog post</a>, allows thread local storage (TLS).
            </p>
        </div>
        <div id="compiler_visible" class="release-note">
            <h4>Added compiler_visible annotation modifier</h4>
            <p>
                New annotation/modifier used to set a field or function's visbility to public before code-gen.
            </p>
        </div>
        <div id="external_name" class="release-note">
            <h4>Added external_name annotation modifier</h4>
            <p>
                New annotation/modifier used to set the outputted name in the external source.
            </p>
        </div>
        <div id="tls-exception-data" class="release-note">
            <h4>Updated ExceptionData to be kept track of through <a ui-sref="blog.thread-local-storage">TLS</a> instead of being passed by parameter</h4>
            <p>
                ExceptionData is a structure that is used to keep track of what types of exceptions are being caught and where they are being caught at. Previously, every function required an ExceptionData parameter to be supplied. This offers slightly better performance over TLS, but is not good for compatibility of function references across external code. For instance, if an external C function were to interface with a Nova function reference, it would have to specify the second parameter as ExceptionData:
            </p>
            <p>
                With the following Nova function definition:
            </p>
            <div hljs language="java" hljs-no-escape>
                class FancyClass {
                    public static myFancyFunc(String something) {
                        Console.writeLine(something)
                    }
                }
            </div>
            <p>
                And external C code:
            </p>
            <div hljs language="c" hljs-no-escape>
                typedef void (*funcReference)(void*, nova_exception_Nova_ExceptionData*, nova_Nova_String*);
                
                void my_external_func(funcReference ref) {
                    // Passing 0 as first argument for the 'this' parameter of the function because
                    // the myFancyFunc is static and does not use the reference parameter.
                    
                    // Passing 0 as second argument because there is no ExceptionData in this context
                    // available to pass! This is what has been fixed...
                    ref(0, 0, nova_Nova_String_1_Nova_construct(0, 0, "Hello, world"));
                    
                    // The first and second argument of nova_Nova_String_1_Nova_construct are 0
                    // for the same reasons as stated above.
                }
            </div>
            <p>
                This is the general idea of the code that was required to call a function reference that was passed from Nova. Now, the second parameter of type nova_exception_Nova_ExceptionData* has been removed. The function implementation would now look like:
            </p>
            <div hljs language="c" hljs-no-escape>
                typedef void (*funcReference)(void*, nova_Nova_String*);
                
                void my_external_func(funcReference ref) {
                    // No need for passing a second 0
                    ref(0, nova_Nova_String_1_Nova_construct(0, "Hello, world"));
                }
            </div>
            <p>
                This approach is cleaner and <b>safer</b>. Because the exceptionData variable is referenced from TLS by Nova generated code, in instances such as the previous code where external code is calling Nova generated code, the ExceptionData is always available. In the previous code, if an exception was thrown somewhere insided the funcReference function call, there would have been a segmentation fault. This is because we were passing in 0 as the ExceptionData. Referencing it from TLS removes the responsibility from the user to pass ExceptionData in external code.
            </p>
        </div>
        <div id="bug-fixes" class="release-note">
            <h4>General bug fixes <issue values="[{number: 367, repo: 'Nova'}]"></issue></h4>
            <p>
                Fixed some bugs with primtive overloads <issue values="[{number: 367, repo: 'Nova'}]"></issue>.
            </p>
        </div>
    </div>
</div>